on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy HTML, CSS, and JS
        run: echo "Deployment steps for static files (HTML, CSS, JS) go here"
